import swaggerAutogen from 'swagger-autogen';
//IMPORT DEFINITIONS HERE
import companyLogoDefinitions from "./features/companyLogos/companyLogoDefinitions.js";
import formDefinitions from "./features/forms/formDefinitions.js";
import organizationDefinitions from "./features/organizations/organizationDefinitions.js";
import portfolioDefinitions from "./features/portfolios/portfolioDefinitions.js";
import serviceDefinitions from "./features/services/serviceDefinitions.js";


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "addboost360debug.epoqzero.com",
    basePath: "/",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [

    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
    },
    definitions: {
        myBoolean: true,
        myNumber: 123,
        myString: 'my example',
        LoginData: { Token: "string", RefreshToken: "string", CurrentUser: { Role: "User", UserId: "" } },
        RefreshTokenData: { Token: "string", RefreshToken: "string" },
        // USE DEFINITIONS HERE
        ...companyLogoDefinitions,
        ...formDefinitions,
        ...organizationDefinitions,
        ...portfolioDefinitions,
        ...serviceDefinitions,
    }

}





const generateSwaggerDocs = async () => {

    const endpointsFiles = ['./routes.js']
    const outputFile = './swaggerOutput.json';

    swaggerAutogen(outputFile, endpointsFiles, doc)
};

generateSwaggerDocs();