import swaggerAutogen from 'swagger-autogen';
//IMPORT DEFINITIONS HERE
import serviceDefinitions from "./features/service/serviceDefinitions.js";


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "api.example.com",
    basePath: "/",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
       
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
    },
    definitions: {
        // USE DEFINITIONS HERE
        ...serviceDefinitions,
    }

}





const generateSwaggerDocs = async () => {

    const endpointsFiles = ['./routes.js']
    const outputFile = './swaggerOutput.json';

    swaggerAutogen(outputFile, endpointsFiles, doc)
};

generateSwaggerDocs();